Repository HangfireIO/Hangfire, pull requests merged in 2019-12, with the labels that each got.

#1575 add netcoreapp3.0 target for .Net Core 3 compatibility
  src/Hangfire.AspNetCore/Hangfire.AspNetCore.csproj
  src/Hangfire.AspNetCore/HangfireApplicationBuilderExtensions.cs
Labels: a: dotnetcore, t: bug

#1577 Add MapHangfireDashboard for ASP.NET Core endpoint routing
  src/Hangfire.AspNetCore/BackgroundJobServerHostedService.cs
  src/Hangfire.AspNetCore/Hangfire.AspNetCore.csproj
  src/Hangfire.AspNetCore/HangfireEndpointRouteBuilderExtensions.cs
  src/Hangfire.AspNetCore/HangfireServiceCollectionExtensions.cs
Labels: a: dotnetcore, t: enhancement

#1588 fix typo in readme file
  README.md
Labels: a: project, t: bug

#1585 Added null checks for expired failed jobs
  src/Hangfire.Core/Dashboard/Pages/FailedJobsPage.cshtml
  src/Hangfire.Core/Dashboard/Pages/FailedJobsPage.cshtml.cs
Labels: a: dashboard, t: bug
